version: "3.7"

services:
  app-back:
    build: .
    container_name: ecorr
    ports:
      - 3333:3333
    environment:
      POSTGRES_HOST: postgres
      PORT: 3333
    depends_on:
      - postgres
    links:
      - postgres
  postgres:
    container_name: postgres_ecorr
    image: postgres
    restart: always
    ports:
      - 5432:5432
    environment:
      POSTGRES_PASSWORD: ecorr
      POSTGRES_DB: ecorr
